// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsBookingSystem.Core.Models;

public partial class BookingDetail
{
    public Guid Id { get; set; }

    public Guid BookingId { get; set; }

    public Guid CourtId { get; set; }

    public int TimeSlotId { get; set; }

    public DateOnly BookingDate { get; set; }

    public decimal PriceAtBookingTime { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Court Court { get; set; }

    public virtual TimeSlot TimeSlot { get; set; }
}