// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsBookingSystem.Core.Models;

public partial class Court
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public int SportTypeId { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<CourtPriceRule> CourtPriceRules { get; set; } = new List<CourtPriceRule>();

    public virtual SportType SportType { get; set; }
}