// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsBookingSystem.Core.Models;

public partial class PaymentTransaction
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentGateway { get; set; }

    public string TransactionCode { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}