// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsBookingSystem.Core.Models;

public partial class SportType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Court> Courts { get; set; } = new List<Court>();
}