// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsBookingSystem.Infrastructure.Data;

#nullable disable

namespace SportsBookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(SportsBookingSystemContext))]
    partial class SportsBookingSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsBookingSystem.Core.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Bookings__3214EC07B5B4E5AA");

                    b.HasIndex(new[] { "UserId" }, "IX_Bookings_UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.BookingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtBookingTime")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BookingD__3214EC072CDD5B6F");

                    b.HasIndex("BookingId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex(new[] { "CourtId" }, "IX_BookingDetails_CourtId");

                    b.HasIndex(new[] { "CourtId", "BookingDate", "TimeSlotId" }, "UQ_NoDoubleBooking")
                        .IsUnique();

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SportTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Courts__3214EC0775E75924");

                    b.HasIndex("SportTypeId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.CourtPriceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__CourtPri__3214EC073C0B1B8F");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtPriceRules");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__PaymentT__3214EC07EF31961A");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.SportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__SportTyp__3214EC0709BC0E90");

                    b.HasIndex(new[] { "Name" }, "UQ__SportTyp__737584F650B698A9")
                        .IsUnique();

                    b.ToTable("SportTypes");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__TimeSlot__3214EC0743E5C44F");

                    b.HasIndex(new[] { "StartTime", "EndTime" }, "UQ_TimeSlot")
                        .IsUnique();

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0784634A6C");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340AE3506A")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__WalletTr__3214EC078053FAA1");

                    b.HasIndex(new[] { "UserId" }, "IX_WalletTransactions_UserId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.Booking", b =>
                {
                    b.HasOne("SportsBookingSystem.Core.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__UserId__4E88ABD4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.BookingDetail", b =>
                {
                    b.HasOne("SportsBookingSystem.Core.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingDe__Booki__534D60F1");

                    b.HasOne("SportsBookingSystem.Core.Models.Court", "Court")
                        .WithMany("BookingDetails")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingDe__Court__5441852A");

                    b.HasOne("SportsBookingSystem.Core.Models.TimeSlot", "TimeSlot")
                        .WithMany("BookingDetails")
                        .HasForeignKey("TimeSlotId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingDe__TimeS__5535A963");

                    b.Navigation("Booking");

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.Court", b =>
                {
                    b.HasOne("SportsBookingSystem.Core.Models.SportType", "SportType")
                        .WithMany("Courts")
                        .HasForeignKey("SportTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Courts__SportTyp__4222D4EF");

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.CourtPriceRule", b =>
                {
                    b.HasOne("SportsBookingSystem.Core.Models.Court", "Court")
                        .WithMany("CourtPriceRules")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK__CourtPric__Court__46E78A0C");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.PaymentTransaction", b =>
                {
                    b.HasOne("SportsBookingSystem.Core.Models.User", "User")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PaymentTr__UserI__5EBF139D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.WalletTransaction", b =>
                {
                    b.HasOne("SportsBookingSystem.Core.Models.User", "User")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__WalletTra__UserI__59FA5E80");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.Court", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("CourtPriceRules");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.SportType", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.TimeSlot", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("SportsBookingSystem.Core.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
